"""
Application entry point.

Run with: uvicorn app.main:app --reload
Interactive API documentation is auto-generated by FastAPI and served
at /docs (Swagger UI) and /redoc.
"""

import os
from fastapi import FastAPI, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.exceptions import RequestValidationError
from sqlalchemy.exc import SQLAlchemyError
from dotenv import load_dotenv

from app.config import settings
from app.api.v1.router import api_router
from app.database import engine, Base

# Load environment variables
load_dotenv()

# Create tables on startup (for production if needed)
# Base.metadata.create_all(bind=engine)

app = FastAPI(
    title=settings.PROJECT_NAME,
    description="API for the university maintenance and service request management platform.",
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ============================================================================
# CORS Configuration
# ============================================================================
# Get allowed origins from settings
allowed_origins = settings.BACKEND_CORS_ORIGINS

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ============================================================================
# Exception Handlers
# ============================================================================


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    return JSONResponse(
        status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
        content={"detail": "Validation failed", "errors": exc.errors()},
    )


@app.exception_handler(SQLAlchemyError)
async def database_exception_handler(request: Request, exc: SQLAlchemyError):
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": "A database error occurred"},
    )


@app.exception_handler(Exception)
async def general_exception_handler(request: Request, exc: Exception):
    return JSONResponse(
        status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
        content={"detail": f"An unexpected error occurred: {str(exc)}"},
    )

# ============================================================================
# Health Check & Root Endpoints
# ============================================================================


@app.get("/", tags=["Health"])
def root():
    return {
        "message": "CampusFix API is running!",
        "status": "healthy",
        "version": "1.0.0",
        "environment": os.getenv("ENVIRONMENT", "development"),
    }


@app.get("/health", tags=["Health"])
def health_check():
    return {"status": "ok", "service": "CampusFix API"}


@app.get("/db-health", tags=["Health"])
def db_health_check():
    """Check database connection health."""
    from sqlalchemy import text
    from app.database import SessionLocal

    try:
        db = SessionLocal()
        result = db.execute(text("SELECT 1"))
        db.close()
        return {
            "status": "connected",
            "message": "Database is healthy",
        }
    except Exception as e:
        return {
            "status": "error",
            "message": f"Database connection failed: {str(e)}",
        }


# ============================================================================
# Include Routers
# ============================================================================
app.include_router(api_router, prefix="/api/v1")

# ============================================================================
# Startup/Shutdown Events
# ============================================================================


@app.on_event("startup")
def on_startup():
    """Run on application startup."""
    print("Starting CampusFix API...")
    print(f"Environment: {os.getenv('ENVIRONMENT', 'development')}")
    print("API is ready!")


@app.on_event("shutdown")
def on_shutdown():
    """Run on application shutdown."""
    print("Shutting down CampusFix API...")
